"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { IconEye, IconRefresh } from "@/components/icons";
import "./adapters-tab.css";

interface AdaptersTabProps {
  detectedAdapters: string[];
  generatedFiles: Array<{ path: string; content: string; ownership: string }>;
  projectStack?: string[];
  onGenerate: (adapterId: string, path: string, content: string) => Promise<void>;
  onRegenerate: (adapterId: string, path: string, content: string) => Promise<void>;
}

const ADAPTERS = [
  { id: "claude-code", name: "Claude Code", file: "CLAUDE.md", devPath: ".dev/adapters/CLAUDE.md", icon: "C", color: "#c084fc", desc: "Points Claude to .dev/ files for project context, conventions, and templates" },
  { id: "cursor", name: "Cursor", file: ".cursorrules", devPath: ".dev/adapters/.cursorrules", icon: "\u2318", color: "#22d3ee", desc: "Loads .dev/ standards into Cursor's context for inline suggestions" },
  { id: "copilot", name: "GitHub Copilot", file: "copilot-instructions.md", devPath: ".dev/adapters/copilot-instructions.md", icon: "\u2299", color: "#8b949e", desc: "References .dev/ coding guidelines for Copilot completions" },
  { id: "windsurf", name: "Windsurf", file: ".windsurfrules", devPath: ".dev/adapters/.windsurfrules", icon: "W", color: "#34d399", desc: "Loads .dev/ context into Windsurf coding sessions" },
  { id: "aider", name: "Aider", file: ".aider.conf.yml", devPath: ".dev/adapters/.aider.conf.yml", icon: "A", color: "#fbbf24", desc: "Includes .dev/ files in Aider's context window" },
  { id: "continue", name: "Continue", file: ".continuerules", devPath: ".dev/adapters/.continuerules", icon: "\u2192", color: "#f472b6", desc: "Maps .dev/ standards to Continue's format" },
];

const DEV_CONTEXT_REFS = [
  "- `.dev/context/PROJECT.md` — Project overview and architecture",
  "- `.dev/context/CONVENTIONS.md` — Coding conventions to follow",
  "- `.dev/context/TECH_DEBT.md` — Known tech debt to be aware of",
  "- `.dev/standards/` — Technology-specific standards for this project",
  "- `.dev/gap-analysis.md` — Industry vs project gap analysis",
].join("\n");

function generateAdapterContent(adapterId: string, stack: string[]): string {
  const stackStr = stack.length > 0 ? stack.join(", ") : "web";

  switch (adapterId) {
    case "claude-code":
      return [
        "# Claude Code Project Config",
        "",
        "Read the following .dev/ files for project context:",
        "",
        DEV_CONTEXT_REFS,
        "",
        "When writing code, follow the conventions and standards defined in these files.",
        "When reviewing code, check against the gap analysis for improvement opportunities.",
      ].join("\n");

    case "cursor":
      return [
        "# Cursor Rules — Auto-generated by buffr",
        "",
        "# Read .dev/ for project intelligence:",
        "# - .dev/context/PROJECT.md for project overview",
        "# - .dev/context/CONVENTIONS.md for coding standards",
        "# - .dev/standards/ for technology-specific patterns",
        "",
        `This is a ${stackStr} project.`,
        "",
        "Follow the conventions and standards in .dev/ when writing code.",
      ].join("\n");

    case "copilot":
      return [
        "# GitHub Copilot Instructions — Auto-generated by buffr",
        "",
        `This is a ${stackStr} project.`,
        "",
        "## Project Context",
        "",
        "Read these .dev/ files for full context:",
        "",
        DEV_CONTEXT_REFS,
        "",
        "Follow the conventions and standards defined in .dev/ when suggesting code.",
      ].join("\n");

    case "windsurf":
      return [
        "# Windsurf Rules — Auto-generated by buffr",
        "",
        "# Project context is stored in .dev/",
        "# Read .dev/context/PROJECT.md for architecture",
        "# Read .dev/context/CONVENTIONS.md for coding standards",
        "# Read .dev/standards/ for technology patterns",
        "",
        `This is a ${stackStr} project.`,
        "",
        "Follow the conventions in .dev/ when writing code.",
      ].join("\n");

    case "aider":
      return [
        "# Aider Config — Auto-generated by buffr",
        "",
        "read:",
        "  - .dev/context/PROJECT.md",
        "  - .dev/context/CONVENTIONS.md",
        "  - .dev/context/TECH_DEBT.md",
        "  - .dev/gap-analysis.md",
      ].join("\n");

    case "continue":
      return [
        "# Continue Rules — Auto-generated by buffr",
        "",
        "# Read .dev/ for project intelligence:",
        "# - .dev/context/PROJECT.md for project overview",
        "# - .dev/context/CONVENTIONS.md for coding standards",
        "# - .dev/standards/ for technology-specific patterns",
        "",
        `This is a ${stackStr} project.`,
        "",
        "Follow the conventions in .dev/ when writing code.",
      ].join("\n");

    default:
      return "";
  }
}

export function AdaptersTab({ detectedAdapters, generatedFiles, projectStack, onGenerate, onRegenerate }: AdaptersTabProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [generatingId, setGeneratingId] = useState<string | null>(null);

  async function handleGenerate(adapter: typeof ADAPTERS[number]) {
    setGeneratingId(adapter.id);
    try {
      const content = generateAdapterContent(adapter.id, projectStack || []);
      await onGenerate(adapter.id, adapter.devPath, content);
    } finally {
      setGeneratingId(null);
    }
  }

  async function handleRegenerate(adapter: typeof ADAPTERS[number]) {
    setGeneratingId(adapter.id);
    try {
      const content = generateAdapterContent(adapter.id, projectStack || []);
      await onRegenerate(adapter.id, adapter.devPath, content);
    } finally {
      setGeneratingId(null);
    }
  }

  return (
    <div className="adapters-tab">
      <p className="adapters-tab__desc">
        Adapters are thin config files that point your AI coding tool to .dev/ — they reference the universal layer, never duplicate content.
      </p>
      <div className="adapters-tab__list">
        {ADAPTERS.map((adapter) => {
          const isDetected = detectedAdapters.includes(adapter.id);
          const existingFile = generatedFiles.find((f) => f.path === adapter.devPath);
          const isExpanded = expandedId === adapter.id;
          const isGenerating = generatingId === adapter.id;

          return (
            <div key={adapter.id}>
              <div
                className={`adapters-tab__card ${isDetected ? "" : "adapters-tab__card--undetected"}`}
              >
                <div
                  className="adapters-tab__icon"
                  style={{
                    background: `${adapter.color}18`,
                    color: adapter.color,
                    border: `1px solid ${adapter.color}30`,
                  }}
                >
                  {adapter.icon}
                </div>

                <div className="adapters-tab__info">
                  <div className="adapters-tab__name-row">
                    <span className="adapters-tab__name">{adapter.name}</span>
                    {isDetected && (
                      <Badge color="emerald" small>
                        detected
                      </Badge>
                    )}
                    <span className="adapters-tab__file">{adapter.file}</span>
                  </div>
                  <div className="adapters-tab__desc">{adapter.desc}</div>
                </div>

                <div className="adapters-tab__actions">
                  {isDetected || existingFile ? (
                    <>
                      {existingFile && (
                        <Button
                          variant="secondary"
                          size="sm"
                          onClick={() => setExpandedId(isExpanded ? null : adapter.id)}
                        >
                          <IconEye size={13} />
                          {isExpanded ? "Hide" : "Preview"}
                        </Button>
                      )}
                      <Button
                        variant="primary"
                        size="sm"
                        onClick={() => handleRegenerate(adapter)}
                        disabled={isGenerating}
                      >
                        <IconRefresh size={13} />
                        {isGenerating ? "..." : "Regenerate"}
                      </Button>
                    </>
                  ) : (
                    <Button
                      variant="secondary"
                      size="sm"
                      onClick={() => handleGenerate(adapter)}
                      disabled={isGenerating}
                    >
                      {isGenerating ? "Generating..." : "Generate"}
                    </Button>
                  )}
                </div>
              </div>

              {isExpanded && existingFile && (
                <div className="adapters-tab__preview">
                  <div className="adapters-tab__preview-header">
                    <span className="adapters-tab__preview-path">{adapter.devPath}</span>
                  </div>
                  <pre className="adapters-tab__preview-content">
                    {existingFile.content}
                  </pre>
                </div>
              )}
            </div>
          );
        })}
      </div>

    </div>
  );
}
