import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { randomUUID } from 'node:crypto';
import {
  UtcDateSchema,
  isCompletedUtcDate,
  type CollectionWindow,
  type MetricSource,
} from '../contracts/metrics.js';
import type { MetricSourceAdapter } from '../connectors/merchgrid/source.js';
import { AppError } from '../core/errors.js';
import { collectSourcePack } from '../metrics/coordinator.js';
import {
  MerchGridReviewEvidenceSchema,
  toMerchGridReviewEvidence,
  type MerchGridReviewEvidence,
} from '../metrics/evidence.js';
import {
  buildDailyHealthSummary,
  buildWeeklyBusinessReview,
  type DailyHealthSummary,
  type SourceStatus,
  type WeeklyBusinessReview,
} from '../metrics/summaries.js';
import type { MetricSnapshotRepository } from '../storage/metric-snapshots.js';
import type { TraceSink } from '../tracing/events.js';

const SOURCES: readonly MetricSource[] = ['posthog', 'fly_metrics', 'shopify_partner'];

export type MerchGridReviewArtifactRepository = {
  saveDailyHealth(date: string, evidence: MerchGridReviewEvidence): Promise<string>;
  loadDailyHealth(date: string): Promise<MerchGridReviewEvidence | undefined>;
  saveWeeklyReview(through: string, evidence: MerchGridReviewEvidence): Promise<string>;
  loadWeeklyReview(through: string): Promise<MerchGridReviewEvidence | undefined>;
};

export type JsonFileMerchGridReviewArtifactRepositoryOptions = {
  rootDir: string;
};

/** Stores only the whitelisted aggregate evidence projections generated by this source pack. */
export class JsonFileMerchGridReviewArtifactRepository implements MerchGridReviewArtifactRepository {
  private readonly rootDir: string;

  constructor(options: JsonFileMerchGridReviewArtifactRepositoryOptions) {
    this.rootDir = options.rootDir;
  }

  async saveDailyHealth(date: string, evidence: MerchGridReviewEvidence): Promise<string> {
    const validDate = parseDate(date);
    if (evidence.period.kind !== 'daily' || evidence.period.date !== validDate) {
      throw new AppError('validation_failed', 'Daily health artifact period does not match its date');
    }
    const path = join(this.rootDir, 'daily-health', `${validDate}.json`);
    await writeArtifact(path, evidence);
    return path;
  }

  async loadDailyHealth(date: string): Promise<MerchGridReviewEvidence | undefined> {
    return this.loadArtifact(join(this.rootDir, 'daily-health', `${parseDate(date)}.json`));
  }

  async saveWeeklyReview(through: string, evidence: MerchGridReviewEvidence): Promise<string> {
    const validThrough = parseDate(through);
    if (evidence.period.kind !== 'weekly' || evidence.period.current.endDate !== validThrough) {
      throw new AppError('validation_failed', 'Weekly review artifact period does not match its through date');
    }
    const path = join(this.rootDir, 'weekly-reviews', `${validThrough}.json`);
    await writeArtifact(path, evidence);
    return path;
  }

  async loadWeeklyReview(through: string): Promise<MerchGridReviewEvidence | undefined> {
    return this.loadArtifact(join(this.rootDir, 'weekly-reviews', `${parseDate(through)}.json`));
  }

  private async loadArtifact(path: string): Promise<MerchGridReviewEvidence | undefined> {
    let raw: string;
    try {
      raw = await readFile(path, 'utf8');
    } catch (error) {
      if (isNodeError(error) && error.code === 'ENOENT') {
        return undefined;
      }
      throw new AppError('storage_failed', 'MerchGrid review artifact could not be read', { cause: error });
    }

    try {
      return MerchGridReviewEvidenceSchema.parse(JSON.parse(raw));
    } catch (error) {
      throw new AppError('storage_failed', 'MerchGrid review artifact JSON is corrupt', { cause: error });
    }
  }
}

export type MerchGridSourcePackDependencies = {
  adapters: readonly MetricSourceAdapter[];
  repository: MetricSnapshotRepository;
  artifacts: MerchGridReviewArtifactRepository;
  now?: () => Date;
  sourceTimeoutMs?: number;
  emit?: TraceSink['emit'];
};

export type DailyCollectionResult = {
  artifactPath: string;
  sourceStatuses: DailyHealthSummary['sourceStatuses'];
  health: DailyHealthSummary;
};

export type WeeklyReviewResult = {
  artifactPath: string;
  sourceStatuses: Record<MetricSource, SourceStatus>;
  review: WeeklyBusinessReview;
};

/** Collects one completed UTC date and persists its aggregate-only daily evidence artifact. */
export async function runDailyCollection(input: {
  date: string;
  dependencies: MerchGridSourcePackDependencies;
}): Promise<DailyCollectionResult> {
  const currentTime = now(input.dependencies);
  const window = completedUtcWindow(input.date, currentTime);
  const storedSnapshots = await Promise.all(
    input.dependencies.adapters.map((adapter) => input.dependencies.repository.load(adapter.source, window.date)),
  );
  const reusableSnapshots = new Map(
    storedSnapshots.filter((snapshot): snapshot is NonNullable<typeof snapshot> => snapshot?.status === 'complete').map((snapshot) => [snapshot.source, snapshot]),
  );
  const collectedSnapshots = await collectSourcePack({
    adapters: input.dependencies.adapters.filter((adapter) => !reusableSnapshots.has(adapter.source)),
    repository: input.dependencies.repository,
    window,
    sourceTimeoutMs: input.dependencies.sourceTimeoutMs,
    runId: `merchgrid-source-pack:${window.date}`,
    emit: input.dependencies.emit,
    now: () => currentTime,
    backfill: isBackfillDate(window.date, currentTime),
  });
  const snapshotsBySource = new Map([
    ...reusableSnapshots.entries(),
    ...collectedSnapshots.map((snapshot) => [snapshot.source, snapshot] as const),
  ]);
  const snapshots = input.dependencies.adapters
    .map((adapter) => snapshotsBySource.get(adapter.source))
    .filter((snapshot): snapshot is NonNullable<typeof snapshot> => snapshot !== undefined);
  const health = buildDailyHealthSummary({ date: window.date, snapshots });
  const artifactPath = await input.dependencies.artifacts.saveDailyHealth(window.date, toMerchGridReviewEvidence(health));

  return { artifactPath, sourceStatuses: health.sourceStatuses, health };
}

/** Builds the two closed adjacent seven-day review windows from already persisted source snapshots. */
export async function runWeeklyReview(input: {
  through: string;
  dependencies: MerchGridSourcePackDependencies;
}): Promise<WeeklyReviewResult> {
  const through = completedUtcWindow(input.through, now(input.dependencies)).date;
  const current = periodEndingOn(through);
  const previous = periodEndingOn(previousUtcDate(current.startDate));
  const [previousSnapshots, currentSnapshots] = await Promise.all([
    loadPeriod(input.dependencies.repository, previous.startDate, previous.endDate),
    loadPeriod(input.dependencies.repository, current.startDate, current.endDate),
  ]);
  assertCompleteWeeklySnapshotSet(
    [...previousSnapshots, ...currentSnapshots],
    previous.startDate,
    current.endDate,
  );
  const review = buildWeeklyBusinessReview({ previous: previousSnapshots, current: currentSnapshots });
  const artifactPath = await input.dependencies.artifacts.saveWeeklyReview(through, toMerchGridReviewEvidence(review));

  return { artifactPath, sourceStatuses: weeklySourceStatuses(review), review };
}

async function loadPeriod(
  repository: MetricSnapshotRepository,
  fromDate: string,
  throughDate: string,
) {
  const snapshots = await Promise.all(SOURCES.map((source) => repository.list(source, fromDate, throughDate)));
  return snapshots.flat();
}

function assertCompleteWeeklySnapshotSet(
  snapshots: readonly { source: MetricSource; date: string }[],
  fromDate: string,
  throughDate: string,
): void {
  const available = new Set(snapshots.map((snapshot) => `${snapshot.source}/${snapshot.date}`));
  const dates = datesFromThrough(fromDate, throughDate);
  const missing = SOURCES.flatMap((source) => dates
    .map((date) => `${source}/${date}`)
    .filter((key) => !available.has(key)));

  if (missing.length > 0) {
    throw new AppError(
      'storage_failed',
      `Missing weekly metric snapshots (${missing.length}): ${missing.join(', ')}`,
    );
  }
}

function datesFromThrough(fromDate: string, throughDate: string): string[] {
  const current = new Date(`${parseDate(fromDate)}T00:00:00.000Z`);
  const end = parseDate(throughDate);
  const dates: string[] = [];
  while (current.toISOString().slice(0, 10) <= end) {
    dates.push(current.toISOString().slice(0, 10));
    current.setUTCDate(current.getUTCDate() + 1);
  }
  return dates;
}

function completedUtcWindow(date: string, currentTime: Date): CollectionWindow {
  const validDate = parseDate(date);
  if (!isCompletedUtcDate(validDate, currentTime)) {
    throw new RangeError(`Metric window date must be before today in UTC: ${validDate}`);
  }

  const start = new Date(`${validDate}T00:00:00.000Z`);
  const end = new Date(start);
  end.setUTCDate(end.getUTCDate() + 1);
  return { date: validDate, startInclusive: start.toISOString(), endExclusive: end.toISOString() };
}

function periodEndingOn(through: string): { startDate: string; endDate: string } {
  const end = parseDate(through);
  const start = new Date(`${end}T00:00:00.000Z`);
  start.setUTCDate(start.getUTCDate() - 6);
  return { startDate: start.toISOString().slice(0, 10), endDate: end };
}

function previousUtcDate(date: string): string {
  const previous = new Date(`${parseDate(date)}T00:00:00.000Z`);
  previous.setUTCDate(previous.getUTCDate() - 1);
  return previous.toISOString().slice(0, 10);
}

function isBackfillDate(date: string, currentTime: Date): boolean {
  const previousCompletedDay = new Date(
    Date.UTC(currentTime.getUTCFullYear(), currentTime.getUTCMonth(), currentTime.getUTCDate()),
  );
  previousCompletedDay.setUTCDate(previousCompletedDay.getUTCDate() - 1);
  return date < previousCompletedDay.toISOString().slice(0, 10);
}

function weeklySourceStatuses(review: WeeklyBusinessReview): Record<MetricSource, SourceStatus> {
  return Object.fromEntries(
    SOURCES.map((source) => [source, coverageStatus(review.sourceCoverage.current[source])]),
  ) as Record<MetricSource, SourceStatus>;
}

function coverageStatus(coverage: Partial<Record<SourceStatus, number>>): SourceStatus {
  const statuses = Object.entries(coverage).filter(([, count]) => count > 0) as [SourceStatus, number][];
  if (statuses.length === 1 && statuses[0]![1] === 7) {
    return statuses[0]![0];
  }
  return 'partial';
}

function parseDate(value: string): string {
  return UtcDateSchema.parse(value);
}

function now(dependencies: MerchGridSourcePackDependencies): Date {
  return dependencies.now?.() ?? new Date();
}

async function writeArtifact(path: string, evidence: MerchGridReviewEvidence): Promise<void> {
  try {
    await mkdir(dirname(path), { recursive: true });
    const temporary = `${path}.${process.pid}.${randomUUID()}.tmp`;
    await writeFile(temporary, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8');
    await rename(temporary, path);
  } catch (error) {
    throw new AppError('storage_failed', 'MerchGrid review artifact could not be saved', { cause: error });
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}
